apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: test-node:v1.0
    imagePullPolicy: Never
    ports:
    - containerPort: 3000
